export const BANKS = [
  { id: 1, name: "우리은행", originName: "우리은행" },
  { id: 2, name: "한국스탠다드차타드은행", originName: "한국스탠다드차타드은행" },
  { id: 3, name: "아이엠뱅크", originName: "아이엠뱅크" },
  { id: 4, name: "부산은행", originName: "부산은행" },
  { id: 5, name: "광주은행", originName: "광주은행" },
  { id: 6, name: "제주은행", originName: "제주은행" },
  { id: 7, name: "전북은행", originName: "전북은행" },
  { id: 8, name: "경남은행", originName: "경남은행" },
  { id: 9, name: "중소기업은행", originName: "중소기업은행" },
  { id: 10, name: "한국산업은행", originName: "한국산업은행" },
  { id: 11, name: "국민은행", originName: "국민은행" },
  { id: 12, name: "신한은행", originName: "신한은행" },
  { id: 13, name: "농협은행", originName: "농협은행주식회사사" },
  { id: 14, name: "하나은행", originName: "하나은행" },
  { id: 15, name: "케이뱅크", originName: "케이뱅크" },
  { id: 16, name: "수협은행", originName: "수협은행" },
  { id: 17, name: "카카오뱅크", originName: "주식회사 카카오뱅크" },
  { id: 18, name: "토스뱅크", originName: "토스뱅크 주식회사" },
]